import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2025,
      sourceType: "module",
      globals: {
        // Tampermonkey API
        GM_getValue: "readonly",
        GM_setValue: "readonly",
        GM_deleteValue: "readonly",
        GM_addValueChangeListener: "readonly",
        GM_removeValueChangeListener: "readonly",
        GM_registerMenuCommand: "readonly",
        GM_unregisterMenuCommand: "readonly",
        GM_xmlhttpRequest: "readonly",
        GM_info: "readonly",
        // Browser globals not in default env
        scheduler: "readonly",
        screen: "readonly",
        requestAnimationFrame: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        performance: "readonly",
        location: "readonly",
        document: "readonly",
        window: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        queueMicrotask: "readonly",
        structuredClone: "readonly",
        crypto: "readonly",
        URL: "readonly",
        TextDecoder: "readonly",
        Uint8Array: "readonly",
        Int32Array: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Promise: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        SyntaxError: "readonly",
        Infinity: "readonly",
        NaN: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        encodeURIComponent: "readonly",
        decodeURIComponent: "readonly",
        encodeURI: "readonly",
        decodeURI: "readonly",
        atob: "readonly",
        btoa: "readonly",
        fetch: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        Blob: "readonly",
        File: "readonly",
        FormData: "readonly",
        URLSearchParams: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLIFrameElement: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        DocumentFragment: "readonly",
        ShadowRoot: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        EventTarget: "readonly",
        MediaStream: "readonly",
        TextTrack: "readonly",
        TextTrackCue: "readonly",
        VTTCue: "readonly",
        XMLHttpRequest: "readonly",
        DOMParser: "readonly",
        Image: "readonly",
        Symbol: "readonly",
        BigInt: "readonly",
        FinalizationRegistry: "readonly",
        WeakRef: "readonly",
        AggregateError: "readonly",
        URIError: "readonly",
        EvalError: "readonly",
        CompileError: "readonly",
        LinkError: "readonly",
        RuntimeError: "readonly",
        SharedArrayBuffer: "readonly",
        Atomics: "readonly",
        WebAssembly: "readonly",
        matchMedia: "readonly",
        getComputedStyle: "readonly",
        cancelAnimationFrame: "readonly",
        requestAnimationFrame: "readonly",
        ResizeObserver: "readonly",
        CSSStyleSheet: "readonly",
        MediaMetadata: "readonly",
        AudioContext: "readonly",
        OffscreenCanvas: "readonly",
        Clipboard: "readonly",
        ClipboardItem: "readonly",
        Notification: "readonly",
        NotificationEvent: "readonly",
        ServiceWorkerRegistration: "readonly",
        NavigationHistoryEntry: "readonly",
        navigator: "readonly",
        GM_getResourceText: "readonly"
      }
    },
    rules: {
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-constant-condition": "error",
      "no-debugger": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-extra-semi": "error",
      "no-redeclare": "error",
      "no-sparse-arrays": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-caller": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-wrappers": "error",
      "no-throw-literal": "error",
      "no-self-compare": "error",
      "no-template-curly-in-string": "warn",
      "prefer-const": "error",
      "no-var": "error",
      "no-loss-of-precision": "error",
      "no-promise-executor-return": "error",
      "no-self-assign": "error",
      "no-unmodified-loop-condition": "error",
      "no-useless-concat": "error",
      "no-useless-escape": "error",
      "no-void": "error",
      "no-with": "error",
      "no-shadow-restricted-names": "error",
      "no-useless-assignment": "error"
    }
  },
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "bench/**",
      "platform/**"
    ]
  }
];
